In [2]:
import numpy as np

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(2,3)

array([[0.68412017, 0.36672376, 0.94815143],
       [0.50283431, 0.33103704, 0.1998015 ]])

In [11]:
arr = np.array([[1,2,3],[4,5,6]])

In [12]:
arr + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [13]:
arr - 3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [14]:
arr * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [15]:
arr / 4

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [16]:
arr ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [17]:
arr = np.array([1,2,3,4,5])

In [23]:
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

15
3.0
3.0
5
1
1.4142135623730951
