In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [8]:
arr3d = np.array([[1,2],[3,4],[5,6],[7,8]])

In [9]:
print(arr3d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
