In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])

In [3]:
print(arr1)

[1 2 3]


In [4]:
arr2= np.array((1,2,3))

In [5]:
print(arr2)

[1 2 3]


In [10]:
np.full((2,2),8)

array([[8, 8],
       [8, 8]])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.random.rand(2,3)

array([[0.26785257, 0.40648124, 0.77406503],
       [0.63486694, 0.13037476, 0.44742023]])

In [12]:
np.random.randn(3,2)

array([[-1.42497259, -1.29521768],
       [ 0.86720693, -0.86634237],
       [ 1.4759335 , -1.36349802]])

In [13]:
np.random.randint(1, 10, size=(2,3))

array([[9, 1, 8],
       [9, 1, 2]], dtype=int32)

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape into 2 rows and 3 columns
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [22]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])

# Flatten using flatten()
flat_arr = arr2d.flatten()
print(flat_arr)

[1 2 3 4 5 6 7 8 9]


In [23]:
# Flatten using ravel()
flat_arr2 = arr2d.ravel()
print(flat_arr2)

[1 2 3 4 5 6 7 8 9]


In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Join along axis 0 (rows)
joined = np.concatenate((a, b), axis=0)
print(joined)

[[1 2]
 [3 4]
 [5 6]]


In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

vstacked = np.vstack((arr1, arr2))
print(vstacked)

[[1 2 3]
 [4 5 6]]


In [28]:
hstacked = np.hstack((arr1, arr2))
print(hstacked)

[1 2 3 4 5 6]
