In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [4]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr3d = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr3d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(2, 3)

In [9]:
arr.size

6

In [10]:
arr.dtype

dtype('int64')

In [12]:
np.random.rand(3,2)

array([[0.59699042, 0.72906318],
       [0.2528267 , 0.33444125],
       [0.13835958, 0.09833621]])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])