In [1]:
import numpy as np

In [2]:
arr1 = np.arange(100,111)

In [3]:
print(arr1)

[100 101 102 103 104 105 106 107 108 109 110]


In [6]:
arr2 = np.arange(1,13).reshape(4,3)

In [7]:
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
arr3 = np.random.randint(1,51,size=(2,3,2))
print(arr3)

[[[ 5 43]
  [ 9 35]
  [ 1 14]]

 [[12 30]
  [ 6 43]
  [39 15]]]


In [15]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)
print(arr2.nbytes)

2
(4, 3)
12
int64
8
96


In [17]:
arr4 = np.array([1.5,2.3,7.9])
arr5 = arr4.astype(int)
print(arr5)

[1 2 7]


In [18]:
arr = np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [19]:
print(arr[1])

[ 6  7  8  9 10]


In [20]:
print(arr[:,2])

[ 3  8 13 18 23]


In [22]:
arr6 = np.arange(5,16)
print(arr6)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [25]:
print(arr6 * 10)
print(arr6 ** 2)
print(arr6 - 3)

[ 50  60  70  80  90 100 110 120 130 140 150]
[ 25  36  49  64  81 100 121 144 169 196 225]
[ 2  3  4  5  6  7  8  9 10 11 12]


In [26]:
arr7 = np.array([12, 15, 20, 22, 30, 45])

In [34]:
print(np.sum(arr7))
print(np.mean(arr7))
print(np.median(arr7))
print(np.std(arr7))
print(np.min(arr7))
print(np.max(arr7))

144
24.0
21.0
10.969655114602888
12
45


In [35]:
arr8 = np.array([2, 4, 6, 8, 10])

In [41]:
print(arr8[arr8>5])
print(arr8[arr8 % 2 == 0])
print(np.where(arr8 > 5))

[ 6  8 10]
[ 2  4  6  8 10]
(array([2, 3, 4]),)


In [45]:
a = np.array([1,2,3,4]) 
b = np.array([2,2,3,5])

print(a == b)
print(a > b)
print(a < b)
print(a[a == b])

[False  True  True False]
[False False False False]
[ True False False  True]
[2 3]


In [46]:
x = np.array([1,2,3])

In [47]:
print(x + 10)

[11 12 13]


In [48]:
print(x * np.array([2,3,4]))

[ 2  6 12]


In [49]:
x2 = x.reshape(3,1)

In [50]:
print(x2)

[[1]
 [2]
 [3]]


In [51]:
z = np.array([10,20,30])

In [52]:
print(x2 + z)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
